# Generated by Django 6.0.4 on 2026-04-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='badge_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
