# Generated by Django 6.0.4 on 2026-04-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_badge_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='badge_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('analist_ong', 'Analist ONG'), ('analist_cercetare', 'Analist Cercetare'), ('inspector_mediu', 'Inspector de Mediu'), ('garda_coasta', 'Gardă de Coastă'), ('politia_frontiera', 'Poliția de Frontieră'), ('autoritate_navala', 'Autoritate Navală'), ('investigator', 'Investigator'), ('supervizor', 'Supervizor'), ('administrator', 'Administrator Sistem'), ('altul', 'Altul')], max_length=50, null=True, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instituție'),
        ),
    ]
