# Generated by Django 6.0.4 on 2026-04-25 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('protected_species', models.TextField(help_text='Ex: Sturion, Delfin, Păsări rare')),
                ('geometry_json', models.JSONField(help_text='GeoJSON polygon data')),
            ],
        ),
        migrations.CreateModel(
            name='IllegalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ship_name', models.CharField(default='UNKNOWN VESSEL', max_length=100)),
                ('mmsi', models.CharField(blank=True, max_length=20, null=True)),
                ('flag', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence_score', models.IntegerField(default=0, help_text='AI Confidence Score %')),
                ('status', models.CharField(choices=[('UNCONFIRMED', 'AI Detected / Unconfirmed'), ('INVESTIGATING', 'Under Investigation'), ('CONFIRMED', 'Confirmed Illegal Fishing'), ('FALSE_ALARM', 'False Alarm')], default='UNCONFIRMED', max_length=20)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.protectedarea')),
            ],
        ),
    ]
