# Generated by Django 6.0.4 on 2026-04-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='illegalreport',
            name='in_restricted_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='illegalreport',
            name='restricted_area_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
