# Generated by Django 6.0.4 on 2026-04-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_scanreport_illegalreport_scan_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanreport',
            name='report_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
